name: Test React Vite
on: push
jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - name: Get the repothetory code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test aplication
        run: npm test
